# Generated by Django 6.0.2 on 2026-02-04 16:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("alamat", models.TextField()),
                ("deskripsi", models.TextField(blank=True, null=True)),
                (
                    "harga_per_bulan",
                    models.DecimalField(decimal_places=0, max_digits=12),
                ),
                (
                    "luas_kamar",
                    models.CharField(help_text="Contoh: 3x4 m", max_length=50),
                ),
                ("is_ac", models.BooleanField(default=False, verbose_name="Ada AC")),
                (
                    "is_kamar_mandi_dalam",
                    models.BooleanField(
                        default=False, verbose_name="Kamar Mandi Dalam"
                    ),
                ),
                (
                    "is_wifi",
                    models.BooleanField(default=False, verbose_name="Ada WiFi"),
                ),
                ("lokasi", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
