# Generated by Django 6.0.2 on 2026-02-06 07:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FasilitasUmum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("MRT", "Stasiun MRT/LRT/KRL"),
                            ("BUS", "Halte TransJakarta"),
                            ("MALL", "Mall & Pusat Perbelanjaan"),
                            ("MART", "Minimarket (Indomaret/Alfamart)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("lokasi", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("alamat_lengkap", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
