# Generated by Django 6.0.2 on 2026-02-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_fasilitasumum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kost",
            name="deskripsi",
        ),
        migrations.AddField(
            model_name="kost",
            name="gambar_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="kost",
            name="link_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="kost",
            name="is_ac",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="kost",
            name="is_kamar_mandi_dalam",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="kost",
            name="is_wifi",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="kost",
            name="luas_kamar",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
